version: '3.4'

services:
  gpstracking.api.gpstrackings:
    image: ${DOCKER_REGISTRY-}gpstrackingapigpstrackings
    build:
      context: .
      dockerfile: GPSTracking.Api.GPSTrackings\Dockerfile

  gpstracking.api.drivers:
    image: ${DOCKER_REGISTRY-}gpstrackingapidrivers
    build:
      context: .
      dockerfile: GPSTracking.Api.Drivers\Dockerfile

